#Build an ANN model for Drug classification.
This project aims to analyze the relationship between various medical parameters and drug effectiveness.
The dataset consists of patient information, including age, sex, blood pressure levels (BP), cholesterol
levels, sodium-to-potassium ratio (Na_to_K), drug type, and corresponding labels. The goal is to develop
a model that can accurately predict the class or category of a given drug based on its features.
##Tasks:
1: Read the dataset and do data pre-processing.
2: Build the ANN model with (input layer, min 3 hidden layers & output layer).
3: Test the model with random data.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drug200.csv')

In [ ]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
df.shape

(200, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [ ]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['Sex']=le.fit_transform(df.Sex)
df['BP']=le.fit_transform(df.BP)
df['Cholesterol']=le.fit_transform(df.Cholesterol)
df['Drug']=le.fit_transform(df.Drug)

In [ ]:
df.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [ ]:
df['Drug'].value_counts()

Drug
0    91
4    54
1    23
3    16
2    16
Name: count, dtype: int64

In [ ]:
X=df.drop('Drug',axis=1).values
y=df['Drug'].values

In [ ]:
X

array([[23.   ,  0.   ,  0.   ,  0.   , 25.355],
       [47.   ,  1.   ,  1.   ,  0.   , 13.093],
       [47.   ,  1.   ,  1.   ,  0.   , 10.114],
       [28.   ,  0.   ,  2.   ,  0.   ,  7.798],
       [61.   ,  0.   ,  1.   ,  0.   , 18.043],
       [22.   ,  0.   ,  2.   ,  0.   ,  8.607],
       [49.   ,  0.   ,  2.   ,  0.   , 16.275],
       [41.   ,  1.   ,  1.   ,  0.   , 11.037],
       [60.   ,  1.   ,  2.   ,  0.   , 15.171],
       [43.   ,  1.   ,  1.   ,  1.   , 19.368],
       [47.   ,  0.   ,  1.   ,  0.   , 11.767],
       [34.   ,  0.   ,  0.   ,  1.   , 19.199],
       [43.   ,  1.   ,  1.   ,  0.   , 15.376],
       [74.   ,  0.   ,  1.   ,  0.   , 20.942],
       [50.   ,  0.   ,  2.   ,  0.   , 12.703],
       [16.   ,  0.   ,  0.   ,  1.   , 15.516],
       [69.   ,  1.   ,  1.   ,  1.   , 11.455],
       [43.   ,  1.   ,  0.   ,  0.   , 13.972],
       [23.   ,  1.   ,  1.   ,  0.   ,  7.298],
       [32.   ,  0.   ,  0.   ,  1.   , 25.974],
       [57.   ,  1. 

In [ ]:
y

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
X

array([[-1.29159102, -1.040833  , -1.11016894, -0.97043679,  1.28652212],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.4151454 ],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.82855818],
       [-0.988614  , -1.040833  ,  1.32976279, -0.97043679, -1.14996267],
       [ 1.0110343 , -1.040833  ,  0.10979693, -0.97043679,  0.27179427],
       [-1.35218642, -1.040833  ,  1.32976279, -0.97043679, -1.03769314],
       [ 0.28388946, -1.040833  ,  1.32976279, -0.97043679,  0.02643885],
       [-0.20087376,  0.96076892,  0.10979693, -0.97043679, -0.70046821],
       [ 0.9504389 ,  0.96076892,  1.32976279, -0.97043679, -0.12676951],
       [-0.07968296,  0.96076892,  0.10979693,  1.03046381,  0.45567206],
       [ 0.16269866, -1.040833  ,  0.10979693, -0.97043679, -0.59916196],
       [-0.62504158, -1.040833  , -1.11016894,  1.03046381,  0.43221897],
       [-0.07968296,  0.96076892,  0.10979693, -0.97043679, -0.09832049],
       [ 1.79877454, -1.040833  ,  0.1

# Model Building

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape,X_test.shape

((160, 5), (40, 5))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#creating ANN Skeleton
model=Sequential()
model.add(Dense(5, activation='relu')) # input layer
model.add(Dense(32, activation='relu'))  #1st Hidden layer
model.add(Dense(64, activation='relu'))#2nd hidden layer
model.add(Dense(64, activation='relu'))#3rd hidden layer
model.add(Dense(units=len(df['Drug'].unique()), activation='softmax')) #Output Layer

In [ ]:
#Compling ANN model
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
#Training the model
model.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 3ms/step - loss: 1.5066 - accuracy: 0.4500
Epoch 2/100
16/16 [==============================] - 0s 3ms/step - loss: 1.3130 - accuracy: 0.4938
Epoch 3/100
16/16 [==============================] - 0s 3ms/step - loss: 1.1367 - accuracy: 0.5125
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 0.9704 - accuracy: 0.6250
Epoch 5/100
16/16 [==============================] - 0s 3ms/step - loss: 0.8203 - accuracy: 0.6562
Epoch 6/100
16/16 [==============================] - 0s 5ms/step - loss: 0.6925 - accuracy: 0.6875
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 0.5927 - accuracy: 0.7812
Epoch 8/100
16/16 [==============================] - 0s 3ms/step - loss: 0.5234 - accuracy: 0.7875
Epoch 9/100
16/16 [==============================] - 0s 3ms/step - loss: 0.4717 - accuracy: 0.8000
Epoch 10/100
16/16 [==============================] - 0s 3ms/step - loss: 0.4308 - accuracy: 0.8125
Epoch 11/

In [ ]:
y_test

array([4, 0, 4, 3, 0, 0, 0, 4, 1, 4, 1, 4, 0, 1, 2, 0, 2, 4, 3, 0, 2, 4,
       4, 0, 0, 0, 3, 4, 0, 4, 0, 3, 3, 0, 1, 0, 4, 1, 0, 1])

In [ ]:
# Evaluate the model on the test set
y_pred = np.argmax(model.predict(X_test), axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

2/2 [==============================] - 0s 5ms/step
Accuracy: 0.975


# Checking on random data

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
y_p = model.predict((scaler.transform([[61,	0,	1,	0,	18.043]])))

predicted_class = np.argmax(y_p)
predicted_drug = le.inverse_transform([predicted_class])[0]  #inversing the Standard Scaling

print("Predicted Drug:", predicted_drug)

1/1 [==============================] - 0s 28ms/step
Predicted Drug: DrugY
